CREATE TABLE IF NOT EXISTS guestbook (
    id SERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    website VARCHAR(100),
    message VARCHAR(150) NOT NULL,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS music (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE,
    name TEXT NOT NULL,
    album TEXT NOT NULL,
    artist TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
